"""
상수 모듈
Java 프로젝트의 Constants 클래스들과 유사한 기능 제공
"""

from .common_constants import *
from .config_constants import *
from .message_constants import *

__all__ = [
    # ==================== CommonConstants ====================
    # 파일 확장자
    "TXT_EXTENSION", "MD_EXTENSION", "PDF_EXTENSION", "DOCX_EXTENSION",
    
    # 문서 폴더 관련
    "DOCUMENTS_FOLDER_NAME", "SYSTEM_USER_DIR",
    
    # 메타데이터 키
    "METADATA_KEY_FILENAME", "METADATA_KEY_FILEPATH", "METADATA_KEY_CHUNK_ID", "METADATA_KEY_CHUNK_INDEX",
    "METADATA_KEY_SAVED_AT", "METADATA_KEY_TITLE", "METADATA_KEY_SECTION_TYPE", "METADATA_KEY_START_LINE",
    "METADATA_KEY_HEADER", "METADATA_KEY_HEADER_LINE", "METADATA_KEY_BODY_SUMMARY", "METADATA_KEY_H1",
    "METADATA_KEY_H2", "METADATA_KEY_H3", "METADATA_KEY_HEADING_LEVEL", "METADATA_KEY_PARAGRAPH_INDEX",
    "METADATA_KEY_CHUNK_LENGTH", "METADATA_KEY_DISTANCE", "METADATA_KEY_VECTOR_SCORE", "METADATA_KEY_FILE_CHUNK_INDEX",
    
    # 내용 키
    "KEY_CONTENT", "KEY_METADATA", "KEY_ERROR",
    
    # README 관련
    "README_FILENAME",
    
    # 기타 공통 상수
    "EMPTY_STRING", "NEWLINE", "SPACE",
    
    # 파서 관련 상수
    "PARSER_HIERARCHICAL", "PARSER_BULLET", "PARSER_SIMPLE_LINE", "ERROR_UNKNOWN_PARSER",
    
    # 정규식 패턴
    "PATTERN_HIERARCHICAL", "PATTERN_BULLET",
    
    # Map 키 상수
    "KEY_EXISTS", "KEY_PATH", "KEY_FILE_COUNT", "KEY_FILES", "KEY_SAVED_AT",
    
    # 기본 상수
    "DEFAULT_ENCODING", "DEFAULT_CHUNK_SIZE", "DEFAULT_CHUNK_OVERLAP", "DEFAULT_CHARSET", "DEFAULT_SERVER_PORT",
    
    # 파서 관련 추가 상수
    "DEFAULT_PARENT_TITLE", "SECTION_TYPE_BULLET", "SECTION_TYPE_MARKDOWN", "SECTION_TYPE_BULLET_WITH_HEADER",
    "SECTION_TYPE_PARAGRAPH",
    
    # 제목 레벨
    "HEADING_LEVEL_1", "HEADING_LEVEL_2", "HEADING_LEVEL_3",
    
    # 길이 제한 상수
    "MAX_TITLE_LENGTH", "TRUNCATED_TITLE_LENGTH", "COLON_LIMIT_LENGTH", "MIN_TABLE_COLUMNS",
    "MAX_HEADER_LENGTH", "MAX_BODY_SUMMARY_LENGTH", "TRUNCATED_BODY_SUMMARY_LENGTH",
    "MAX_CHUNK_LENGTH", "MIN_CHUNK_LENGTH", "MIN_TITLE_LENGTH",
    
    # 기타 상수
    "ELLIPSIS", "WILDCARD",
    
    # 포맷 문자열
    "SECTION_FORMAT", "HIERARCHY_FORMAT",
    
    # Markdown 관련 상수
    "MARKDOWN_HEADING_PATTERN", "MARKDOWN_HEADING_PATTERN_1_3", "H1_PREFIX", "H2_PREFIX", "H3_PREFIX",
    "TITLE_SEPARATOR", "MIN_MARKDOWN_HEADINGS",
    
    # 문장 분리 정규식
    "SENTENCE_SPLIT_REGEX", "TITLE_SENTENCE_SPLIT_REGEX", "PARAGRAPH_SEPARATOR",
    
    # ==================== ConfigConstants ====================
    # 설정 키
    "CONFIG_DOCUMENTS_FOLDER", "CONFIG_VECTORSTORE_TYPE", "CONFIG_VECTORSTORE_INDEX_NAME",
    "CONFIG_VECTORSTORE_KEY_PREFIX", "CONFIG_VECTORSTORE_EMBEDDING_PREFIX",
    "CONFIG_SEARCH_THRESHOLD", "CONFIG_SEARCH_MAX_RESULTS",
    
    # 기본값
    "DEFAULT_DOCUMENTS_FOLDER", "DEFAULT_VECTORSTORE_TYPE", "DEFAULT_SEARCH_THRESHOLD", "DEFAULT_MAX_RESULTS",
    "DEFAULT_OLLAMA_CHAT_MODEL", "DEFAULT_OLLAMA_EMBEDDING_MODEL", "DEFAULT_OLLAMA_BASE_URL",
    "DEFAULT_REDIS_HOST", "DEFAULT_REDIS_PORT", "DEFAULT_REDIS_DATABASE",
    
    # Redis 관련 상수
    "REDIS_KEY_PREFIX", "REDIS_DOCUMENT_KEY_PREFIX", "REDIS_EMBEDDING_KEY_PREFIX",
    "VECTOR_INDEX_NAME", "VECTORSTORE_PREFIX",
    
    # 설정 맵 키 상수
    "MAP_KEY_DOCUMENTS_FOLDER", "MAP_KEY_PROCESSING_DOCUMENTS_FOLDER", "MAP_KEY_INDEX_NAME",
    "MAP_KEY_KEY_PREFIX", "MAP_KEY_EMBEDDING_PREFIX",
    
    # API 응답 맵 키
    "MAP_KEY_SAVED_COUNT", "MAP_KEY_DUPLICATE_COUNT", "MAP_KEY_TOTAL_COUNT", "MAP_KEY_DOCUMENT_COUNT",
    "MAP_KEY_MESSAGE", "MAP_KEY_IS_INITIALIZED", "MAP_KEY_LOADED_FILES", "MAP_KEY_REDIS_CONNECTION",
    "MAP_KEY_VECTOR_STORE_TYPE", "MAP_KEY_TOTAL_DELETED", "MAP_KEY_RAG_KEYS_DELETED", "MAP_KEY_EMBEDDING_KEYS_DELETED",
    "MAP_KEY_RAG_KEYS", "MAP_KEY_EMBEDDING_KEYS", "MAP_KEY_ANSWER", "MAP_KEY_SOURCES", "MAP_KEY_SUCCESS",
    "MAP_KEY_ORIGINAL_FILE_COUNT",
    
    # 컨트롤러 관련 상수
    "REDIS_CONNECTION_CONNECTED", "REDIS_CONNECTION_DISCONNECTED", "VECTORSTORE_TYPE_SIMPLE_REDIS_BACKUP",
    
    # 메시지 상수
    "MSG_REDIS_CONNECTION_CHECK", "MSG_REDIS_STATUS_CHECK_FAILED", "MSG_REDIS_VECTORSTORE_DELETE_COMPLETE",
    "MSG_REDIS_VECTORSTORE_DELETE_FAILED", "MSG_REDIS_VECTORSTORE_BUILD_FAILED", "MSG_DOCUMENTS_RELOADED",
    "MSG_DOCUMENT_RELOAD_FAILED", "MSG_REDIS_KEY_DELETE_ERROR", "MSG_DOCUMENT_PROCESSING_STARTED",
    "MSG_BACKGROUND_PROCESSING",
    
    # SourceInfo 관련 상수
    "TITLE_PREFIX_BRACKET_START", "TITLE_PREFIX_BRACKET_END", "TITLE_PREFIX_MARKDOWN", "TITLE_PREFIX_KOREAN",
    "SCORE_DECIMAL_FORMAT", "UNKNOWN_FILENAME", "UNKNOWN",
    
    # 리소스 경로 상수
    "RESOURCE_CLASSPATH_PREFIX",
    
    # toString 포맷
    "VECTORSTORE_CONFIG_FORMAT",
    
    # 메타데이터 관련 상수
    "METADATA_CHUNK_ID", "METADATA_SAVED_AT", "METADATA_DISTANCE", "METADATA_VECTOR_SCORE", "JSON_KEY_METADATA",
    
    # 로그 메시지
    "LOG_DOCUMENT_STATUS_CHECK_FAILED", "LOG_METADATA_JSON_PARSE_FAILED", "LOG_FILE_LOAD_FAILED",
    "LOG_UNEXPECTED_ERROR", "LOG_DOCUMENT_PROCESS_FAILED", "LOG_REDIS_VECTORSTORE_STATUS_FAILED",
    "LOG_REDIS_STATUS_CHECK_ERROR",
    
    # ==================== MessageConstants ====================
    # 에러 관련 상수
    "ERROR_DOCUMENT_LOAD_FAILED", "ERROR_VECTORSTORE_INIT_FAILED", "ERROR_REDIS_LOAD_FAILED",
    "ERROR_SEARCH_FAILED", "ERROR_INVALID_ARGUMENT",
    
    # 에러 타입
    "ERROR_TYPE_INTERNAL_SERVER", "ERROR_TYPE_RUNTIME", "ERROR_TYPE_RAG_SERVICE", "ERROR_TYPE_INVALID_ARGUMENT",
    
    # API 응답 키 상수
    "RESPONSE_KEY_SUCCESS", "RESPONSE_KEY_TIMESTAMP", "RESPONSE_KEY_ERROR", "RESPONSE_KEY_MESSAGE",
    "RESPONSE_KEY_PATH", "RESPONSE_KEY_STATUS",
    
    # 사용자 응답 메시지
    "MSG_NO_RELEVANT_INFO", "MSG_NO_RELIABLE_INFO", "MSG_NO_KNOWLEDGE_BASE",
    
    # 상태 메시지 상수
    "MSG_DOCUMENTS_LOADED", "MSG_DOCUMENTS_NOT_LOADED", "MSG_VECTORSTORE_MARKED_INITIALIZED",
    "MSG_FILE_LOAD_SUCCESS", "MSG_FILE_LOAD_FAILED_PREFIX", "MSG_ERROR_PREFIX",
    
    # 메시지 상수
    "MSG_FOLDER_NOT_EXISTS", "MSG_NO_TEXT_FILES", "MSG_FILES_PROCESSED",
    
    # 성공 메시지
    "MSG_VECTORSTORE_DATA_CLEANED", "MSG_VECTORSTORE_INIT_ERROR",
    
    # 시스템 메시지
    "MSG_SYSTEM_READY", "MSG_SYSTEM_NOT_READY", "MSG_NO_DOCUMENTS_LOADED",
    
    # 검색 관련 메시지
    "MSG_NO_RELEVANT_INFO_FOUND", "MSG_AI_ANSWER_ERROR",
    
    # 데이터 로드 요청 메시지
    "LOG_MANUAL_LOAD_REQUEST",
    
    # VectorStore 데이터 관련 메시지
    "MSG_VECTORSTORE_CLEAN_ERROR", "MSG_VECTORSTORE_INIT_ERROR",
    
    # Redis 로드 관련 상수
    "MSG_REDIS_NO_DOCUMENTS", "MSG_REDIS_LOAD_SUCCESS", "MSG_REDIS_LOAD_FAILED", "MSG_REDIS_LOAD_ERROR",
    
    # 문서 처리 메시지
    "LOG_DOCUMENT_PROCESS_FAILED"
]
