"""
상수 모듈
"""

from .common_constants import *
from .config_constants import *
from .message_constants import *

__all__ = [
    # CommonConstants
    "TXT_EXTENSION", "MD_EXTENSION", "PDF_EXTENSION", "DOCX_EXTENSION",
    "METADATA_KEY_FILENAME", "METADATA_KEY_FILEPATH", "METADATA_KEY_CHUNK_INDEX", "METADATA_KEY_SAVED_AT",
    "DOCUMENTS_FOLDER_NAME", "KEY_EXISTS", "KEY_FILES",
    "DEFAULT_ENCODING", "DEFAULT_CHUNK_SIZE", "DEFAULT_CHUNK_OVERLAP",
    
    # ConfigConstants
    "MAP_KEY_SAVED_COUNT", "MAP_KEY_DUPLICATE_COUNT", "MAP_KEY_TOTAL_COUNT", "MAP_KEY_DOCUMENT_COUNT",
    "MAP_KEY_MESSAGE", "MAP_KEY_IS_INITIALIZED", "MAP_KEY_LOADED_FILES", "MAP_KEY_REDIS_CONNECTION",
    "MAP_KEY_VECTOR_STORE_TYPE", "MAP_KEY_TOTAL_DELETED", "MAP_KEY_RAG_KEYS_DELETED", "MAP_KEY_EMBEDDING_KEYS_DELETED",
    "MAP_KEY_RAG_KEYS", "MAP_KEY_EMBEDDING_KEYS", "MAP_KEY_ANSWER", "MAP_KEY_SOURCES",
    "REDIS_CONNECTION_CONNECTED", "REDIS_CONNECTION_DISCONNECTED", "VECTORSTORE_TYPE_SIMPLE_REDIS_BACKUP",
    "MSG_REDIS_CONNECTION_CHECK", "MSG_REDIS_STATUS_CHECK_FAILED", "MSG_REDIS_VECTORSTORE_DELETE_COMPLETE",
    "MSG_REDIS_VECTORSTORE_DELETE_FAILED", "MSG_REDIS_VECTORSTORE_BUILD_FAILED", "MSG_DOCUMENTS_RELOADED",
    "MSG_DOCUMENT_RELOAD_FAILED", "MSG_REDIS_KEY_DELETE_ERROR", "LOG_DOCUMENT_STATUS_CHECK_FAILED",
    "LOG_METADATA_JSON_PARSE_FAILED",
    
    # MessageConstants
    "MSG_VECTORSTORE_DATA_CLEANED", "MSG_VECTORSTORE_INIT_ERROR", "MSG_FOLDER_NOT_EXISTS",
    "MSG_NO_TEXT_FILES", "LOG_DOCUMENT_PROCESS_FAILED", "MSG_SYSTEM_READY", "MSG_SYSTEM_NOT_READY",
    "MSG_DOCUMENTS_LOADED", "MSG_NO_DOCUMENTS_LOADED"
]
